FROM continuumio/miniconda3

COPY ./ /

USER root
RUN apt-get update \
        && apt-get -y install --no-install-recommends apt-utils dialog 2>&1 \
        #
        # Verify git, process tools, lsb-release (common in install instructions for CLIs) installed
        && apt-get -y install git iproute2 procps iproute2 lsb-release \
        #
        # Clean up
        && apt-get autoremove -y \
        && apt-get clean -y \
        && rm -rf /var/lib/apt/lists/*


RUN /bin/bash -c "source ~/.bashrc"

RUN pip install psycopg2-binary
RUN pip install mysql-connector-python
RUN pip install google-cloud-bigquery
RUN pip install PyYAML
RUN pip install schedule
RUN pip install celery
RUN pip install redis
RUN conda install --y --file /requirements.txt
RUN conda install -y -c conda-forge fbprophet
RUN pip install tensorflow==2.2.0
RUN conda install keras




EXPOSE 3536
EXPOSE 1433
CMD ["python", "/model_api.py"]



